### ISSUE TITLE
Docx File open get error

### ISSUE THREAD

**Issue by sureshopensoft** [vench/vsword#1]
Its Very Nice lib ....Thanks to doing a good job. I am try to create word file in doc& docx format but it gives error like
![1](https://cloud.githubusercontent.com/assets/11133517/6313682/a93bc850-b9df-11e4-9dc0-998dc417b8ed.jpg)
![2](https://cloud.githubusercontent.com/assets/11133517/6313683/b14cb4e6-b9df-11e4-894f-02587b57920c.jpg)
![3](https://cloud.githubusercontent.com/assets/11133517/6313685/bd5ee614-b9df-11e4-9db5-cd6ed9077aac.jpg)

**Comment by vench** [comment]
Well. Send me please you source code to email nowwrit@mail.ru

**Comment by sureshopensoft** [comment]
Thanks Vench ......... I send mail to you.........

**Comment by vench** [comment]
Hello. To parse the file you want to use a method parseFrotUrl. In any case, send another html file itself.

**Comment by sureshopensoft** [comment]
ok I will try and tel the result to you....

**Comment by sureshopensoft** [comment]
I try it ...The output file have content but also have same error in in file opening same as I mention 1st errors.......and also more line space have in output .....

**Comment by vench** [comment]
Okay. And the html file can be viewed

**Comment by sureshopensoft** [comment]
still the same problem in file opening.....

**Comment by vench** [comment]
send me html file or link here

**Comment by sureshopensoft** [comment]
<html>
 <HEAD>
<TITLE>Basic HTML Sample Page</TITLE>
</HEAD>
<BODY BGCOLOR="WHITE">
<CENTER>
<H1>A Simple Sample Web Page</H1>  
</body>
</html>

**Comment by vench** [comment]
<html>
 <HEAD>
<TITLE>Basic HTML Sample Page</TITLE>
</HEAD>
<BODY BGCOLOR="WHITE">
<CENTER>

<H1>A Simple Sample Web Page</H1> 

</body>
</html>

Tag "CENTER" must be closed

**Comment by sureshopensoft** [comment]
Even i closed tag then also i got same problem...send your file ......

**Comment by vench** [comment]
Look at new example  https://github.com/vench/vsword/commit/12f73149e230d6933ce4ba3c22b489eb044dd481

I have it working correctly

**Comment by sureshopensoft** [comment]
Hello vench i got again same error when i use new code ....please send your
output file......

On Tue, Feb 24, 2015 at 5:36 PM, vench notifications@github.com wrote:

> Look at new example 12f7314
> https://github.com/vench/vsword/commit/12f73149e230d6933ce4ba3c22b489eb044dd481
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vench/vsword/issues/1#issuecomment-75745083.

## 

Suresh.C
Software Engineer Trainee,
Open Soft

I'm Not Prefect But I want Become a Perfect......

**Comment by sureshopensoft** [comment]
When I open your output file also got same error vench......

**Comment by vench** [comment]
Unusual.
I have Office 2010, perhaps that's the problem? I also tested the open office.

**Comment by sureshopensoft** [comment]
I tested Ms Office 2007 and Open office 3.4.0

**Comment by vench** [comment]
I look in the 2007 version.

**Comment by sureshopensoft** [comment]
ok

**Comment by vench** [comment]
I will help if you send an example of the working of his file.

**Comment by sureshopensoft** [comment]
output file u sent also didn't not working...

**Comment by vench** [comment]
just an empty file that works for you (somefile.docx)

**Comment by sureshopensoft** [comment]
no that is have content

On Tue, Feb 24, 2015 at 6:32 PM, vench notifications@github.com wrote:

> just an empty file that works for you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vench/vsword/issues/1#issuecomment-75752258.

## 

Suresh.C
Software Engineer Trainee,
Open Soft

I'm Not Prefect But I want Become a Perfect......

**Comment by sureshopensoft** [comment]
In libre office4.2.4.2  file open without error vench.....

**Comment by sureshopensoft** [comment]
In office2010  file open without error vench.....

**Comment by vench** [comment]
thank you. I think it will help me

**Comment by sureshopensoft** [comment]
Hi you can also fix me file open in without error in office 2007 that will use everyone.....

**Comment by sureshopensoft** [comment]
Hi vench one more thing when i use numbering style in html it convert into docx that make unwanted line space and In office 2007 image size cant apply ....

**Comment by sureshopensoft** [comment]
Hello vench due you have any idea or php lib to convert doc,docx to html format please share me.....

**Comment by vench** [comment]
i use Microsoft.Office.Professional.Plus.2007.SP2.Integrated and  opened file  without error  ...

**Comment by vench** [comment]
added you

**Comment by sureshopensoft** [comment]
ok i try....you know how to convert doc,docx to html......

**Comment by sureshopensoft** [comment]
![capture](https://cloud.githubusercontent.com/assets/11133517/6426413/c1424be6-bf7e-11e4-9a37-294bf23d0ce7.PNG)
Hi,
  Vench when i convert html to docx i got error like above mentioned manner......
my html code is mail to you vench
