### ISSUE TITLE
Error parsing P elements within a UL structure

### ISSUE THREAD

**Issue by luke-sift** [vench/vsword#10]
Hi

Thanks for a great library. I'm finding the library really useful, however I've noticed MS Word can't open some of the files that our application is exporting.

I'm using the parse method to convert HTML snippets into docx files.

If the following element structure exists, the file is created correctly but it can't be opened by MS Word.

```
<ul>
	<li>
	<p>Text</p>

	<ul>
		<li>List item 1</li>
		<li>List item 2</li>
	</ul>
	</li>
</ul>
```

Thanks

Luke

**Comment by vench** [comment]
hi 
I would be watching this issue.

**Comment by vench** [comment]
Try please this solution https://github.com/vench/vsword/commit/facc144234c421eba79c8b1151d68907bef39bea

**Comment by luke-sift** [comment]
I will try this tonight, thanks

Luke

**Comment by luke-sift** [comment]
Hi

Thanks for the fix. I can confirm it works well.

Cheers

Luke
