### ISSUE TITLE
Notice when parsing HTML

### ISSUE THREAD

**Issue by luke-sift** [vench/vsword#11]
Hi

I'm receiving this notice when parsing HTML:

```Notice: Use of undefined constant ENT_XML1 - assumed 'ENT_XML1' in HTMLLoader->createStringNode() (line 114 of vsword/vsword/parser/HTMLLoader.php).```

Happy to supply more information if required.

Thanks

Luke

**Comment by vench** [comment]
Hi
Fix it in last comment https://github.com/vench/vsword/commit/961a90204228eac19526d66e5909a9f76766f806
Thanks

**Comment by luke-sift** [comment]
Thanks for the quick response

Luke
