### ISSUE TITLE
EmptyCompositeNodeNodeAddeded.php does not exist

### ISSUE THREAD

**Issue by knulo** [vench/vsword#13]
Hi,

source file for EmptyCompositeNodeNodeAddeded (referenced by ) not exists in vsword/parser/addeded.

I use
```
$doc = new VsWord();
$parser = new HtmlParser($doc);
$parser->parse($htmlContent);
```

Because I'm pretty new with your framework, I don't know, if I made an error before, may be in the HTML source. But there should be an error output which explains the reason for presence of an unhandled class (EmptyCompositeNode?) and leads to a solution - right?

Thanks in advance for your effort.

Regards Knut

**Comment by vench** [comment]
Hi. 
Send me  please your HTML code

**Comment by knulo** [comment]
Hi,

see source HTML attached.

-- 
Kind regards
Knut

mailto:knulo@arcor.de

Am 16.02.2017 15:07, schrieb vench:

**Comment by vench** [comment]
Sorry. What is your version PHP?
I think the problem is the interception Exception

**Comment by knulo** [comment]
Sorry for late reply, spent some days in the snow...   ;-)
PHP Version 5.6.30-1~dotdeb+7.1
I figured out, that this 'node' (EmptyCompositeNode) is set for 'unknown' tags (parser.php, line 40, DefaultInitNode.php, line 123) but afterwards there is no 'NodeAdded' handler for that (HtmlParser.php, line 45?).

**Comment by vench** [comment]
Try update version
