### ISSUE TITLE
No whitespaces on google docs

### ISSUE THREAD

**Issue by ghost** [vench/vsword#14]
I just found out from a customer that when he receives the text in a docx document I generate he's able to view the document properly formatted in WordPad and Word 2016 but not in google docs.

It basically loses all whitespaces added to the file.

Is there any way to enforce the whitespace?

**Comment by vench** [comment]
Hi.
Try apply https://github.com/vench/vsword/blob/master/vsword/node/PageBreakNode.php

**Comment by ghost** [comment]
Hi Vench, thanks for trying that fix. unfortunately that didn't solve my issue.

Basically, all new lines are missing when opening them on google docs now, so all the text is clumped up into one "paragraph" instead of being well formatted. This doesn't seem to be the case when opening the file with for example wordPad

**Comment by ghost** [comment]
Hi @vench , 

I've been trying some stuff out and apparently it's the `<br />` tag that won't work. Only certain applications keep the formatting intact, could you guide me on how to make newlines in your software?

**Comment by vench** [comment]
Hey. Sorry for the slow answer.
Fix it https://github.com/vench/vsword/commit/8c285167bbc77f9b5394826c542c15c4d06c0aa5

Update your repository and use)
