### ISSUE TITLE
Library requirements ?

### ISSUE THREAD

**Issue by drzero** [vench/vsword#16]
Thank for library , but i can't run it. I think my php not enable some extension , what library requirements ?

**Comment by kaystrobach** [comment]
what's the error message?

**Comment by drzero** [comment]
HTTP ERROR 500

**Comment by kaystrobach** [comment]
What is in your apache error log or php error log

**Comment by drzero** [comment]
//files  VsWord.php

 public function __construct($from = NULL) {
        if (!class_exists('ZipArchive')) {
            throw new Exception("Class \"ZipArchive\" not found!");
        }

        $this->structure = $this->getBaseStructureDocClasses(); // error here
		
		die('3');
    }

**Comment by kaystrobach** [comment]
So you need php zip extension. On debian you can call:

'apt-get install php5-zip'

On windows you need to enable it in php.ini. Anyway I'm sure you can create a pull request to add this requirement to composer.json.

**Comment by kaystrobach** [comment]
See http://php.net/ZipArchive for details

**Comment by drzero** [comment]
Thank you
