### ISSUE TITLE
How to repeat table header on every page of the word.

### ISSUE THREAD

**Issue by avinash1785** [vench/vsword#18]
Hi Vench,

Thank you for your help.

I want to know that what is the process to repeat table header on every page of the Word document.

Thanks,
Avinash

**Comment by mohsincynexis** [comment]
I am also looking for the same. Can any one of you please guide me on this?

Thank  you.

**Comment by vench** [comment]
Hey.
I think so far only if you do it manually.
Also. You can use page break.
https://github.com/vench/vsword/blob/master/examples/pagebreak.php
