### ISSUE TITLE
Add composer.json and add to packagist.org

### ISSUE THREAD

**Issue by mazurva** [vench/vsword#2]
Add composer.json and add to packagist.org

**Comment by vench** [comment]
Thanks for the idea. Do it.

https://packagist.org/packages/vench/vs-word

**Comment by vench** [comment]
About project http://vench-master.spb.ru/ru/page87/article82

**Comment by mevjak** [comment]
It works. The only drawback is that there is no tagged version of `vench/vsword`, so you should have `"minimum-stability": "dev"` in your project composer.json.

**Comment by vench** [comment]
Add version
