### ISSUE TITLE
Can't make underline appear in text

### ISSUE THREAD

**Issue by dfector** [vench/vsword#3]
I've tried using both the html parser with <u> tags, and the addTextStyle(new \UnderLineStyleNode()) method directly with the nodes.

Am I missing something?  :-(

**Comment by vench** [comment]
see for example 
https://github.com/vench/vsword/blob/master/examples/htmlparser_yourstyle2.php

Add line
$r->addTextStyle(new UnderLineStyleNode());

If you catch error, write it me

**Comment by dfector** [comment]
I was working from the example: base.php

`$rParagraph3 = new \RCompositeNode();`
`$paragraph2->addNode($rParagraph3);`
`$rParagraph3->addTextStyle(new \UnderlineStyleNode());`
`$rParagraph3->addText('Underline text');`
`$body->addNode( $paragraph2 );`

But the text doesn't appear underlined when I open the document.

**Comment by vench** [comment]
Thank you for participating. Fixed bug .

https://github.com/vench/vsword/blob/master/examples/underline.php
