### ISSUE TITLE
Word 2016: Warning Message - "Missing Proofing Tools (for Russian Language)"

### ISSUE THREAD

**Issue by woodwardmatt** [vench/vsword#4]
Was just trying out your library with a sample piece of code from [here](http://www.phpclasses.org/blog/post/315-Create-Microsoft-Word-DOCX-files-from-HTML-in-PHP-Part-1-Simple-Example.html). When I open the generated docx file in word locally I then see a warning appear in Word because I don't have the russian language proofing tools installed.

Here's a screen shot, any thoughts on how I can prevent this warning?

![image](https://cloud.githubusercontent.com/assets/461398/15413411/1287a4d8-1e6f-11e6-841d-8979eb223d98.png)

**Comment by vench** [comment]
Hello.
I do fix it in last commit 

https://github.com/vench/vsword/commit/7738149e2171a1379adc101d4f808c221f0595bd 

If this problem don't  help your, change value https://github.com/vench/vsword/blob/master/vsword/structure/WordDirSettingsStructureDocFile.php#L21  for your locale.

Thanks for the help in the project
