### ISSUE TITLE
Can't add "&" symbol in my text htmlparser.php

### ISSUE THREAD

**Issue by ashok121284** [vench/vsword#8]
Hi I am creating a word file through vsword examples/htmlparser.php. My html content having text which includes "&" symbol. It is like $html = '<p>Terms & Conditions</p>'.  When I am running it the created document only adding "Terms" text. Please answer me how i solve it?

**Comment by vench** [comment]
I thing that is bug.  While use safe text string function htmlspecialchars. We are fast  fix it

**Comment by ashok121284** [comment]
Hi I want to give  default font "Verdana" in place of "Time new Roman". I searched whole document of vsword but i did not get. Can you tell me how can i do it?

**Comment by ghost** [comment]
Have the same issue of OP with `&nbsp;` character
I also have posted [here](http://www.phpclasses.org/discuss/package/8991/thread/16/)
+1

**Comment by vench** [comment]
Hello. I will try to solve this problem in the near future.

**Comment by vench** [comment]
You would use these example https://github.com/vench/vsword/blob/master/examples/space.php
replace &nbsp; character in your string on plain space

**Comment by purplespider** [comment]
Struggling to find a way to use a & symbol in the HTML. I've tried both `&amp;` and `&`. Is there any workaround for this? I've tried using the HTML parser as per the example.

**Comment by luke-sift** [comment]
Hi, is there any update for this issue?

**Comment by vench** [comment]
Fix it in commit https://github.com/vench/vsword/commit/19a8f55f16e6e4b47dbdad3d1274f61daaf7623e

**Comment by purplespider** [comment]
Thanks! Seems to work great!

**Comment by vench** [comment]
If all ok? close this issue please.
