### ISSUE TITLE
Strict (2048): Declaration of DocumentCompositeNode::addNode() should be compatible with CompositeNode::addNode(INode $node)

### ISSUE THREAD

**Issue by krishnatiw** [vench/vsword#9]

**Comment by krishnatiw** [comment]
Please edit following file:
should be compatible with CompositeNode::addNode(INode $node) [\vsword\node\DocumentCompositeNode.php, line 22]

**Comment by vench** [comment]
Please send your code

**Comment by krishnatiw** [comment]
public function addNode(BodyCompositeNode $node) {
		return parent::addNode($node);
	}

to 

public function addNode(INode $node) {
		return parent::addNode($node);
	}

**Comment by vench** [comment]
Ok. Thanks you.
You use php 7 where strict types. I need to add a new branch to php7 and fix it.

**Comment by vench** [comment]
Try Now please

**Comment by krishnatiw** [comment]
Thanks
